/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerCompraCripto;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JTextField;
import model.Investidor;

/**
 *
 * @author luana
 */
public class ComprarCripto extends javax.swing.JFrame {

    /**
     * Creates new form ComprarCripto
     */
    public ComprarCripto(Investidor invest) {
        initComponents();
        setLocationRelativeTo(null);
        investidor = invest;
        control = new ControllerCompraCripto(this, investidor);
        control.fazCarteira();
        control.mostrarCotacao();
    }

    public Investidor getInvestidor() {
        return investidor;
    }

    public void setInvestidor(Investidor investidor) {
        this.investidor = investidor;
    }

    public ControllerCompraCripto getControl() {
        return control;
    }

    public void setControl(ControllerCompraCripto control) {
        this.control = control;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JMenuItem getjMenuItem1() {
        return jMenuItem1;
    }

    public void setjMenuItem1(JMenuItem jMenuItem1) {
        this.jMenuItem1 = jMenuItem1;
    }

    public JMenu getjMenuMenu() {
        return jMenuMenu;
    }

    public void setjMenuMenu(JMenu jMenuMenu) {
        this.jMenuMenu = jMenuMenu;
    }

    public JLabel getLblCompra() {
        return lblCompra;
    }

    public void setLblCompra(JLabel lblCompra) {
        this.lblCompra = lblCompra;
    }

    public JLabel getLblCotacao() {
        return lblCotacao;
    }

    public void setLblCotacao(JLabel lblCotacao) {
        this.lblCotacao = lblCotacao;
    }

    public JLabel getLblCotacaoT() {
        return lblCotacaoT;
    }

    public void setLblCotacaoT(JLabel lblCotacaoT) {
        this.lblCotacaoT = lblCotacaoT;
    }

    public JLabel getLblDecisao() {
        return lblDecisao;
    }

    public void setLblDecisao(JLabel lblDecisao) {
        this.lblDecisao = lblDecisao;
    }

    public JLabel getLblQuant() {
        return lblQuant;
    }

    public void setLblQuant(JLabel lblQuant) {
        this.lblQuant = lblQuant;
    }

    public JLabel getLblReaisRes() {
        return lblReaisRes;
    }

    public void setLblReaisRes(JLabel lblReaisRes) {
        this.lblReaisRes = lblReaisRes;
    }

    public JTextField getTxtMoeda() {
        return txtMoeda;
    }

    public void setTxtMoeda(JTextField txtMoeda) {
        this.txtMoeda = txtMoeda;
    }

    public JTextField getTxtQuantMoeda() {
        return txtQuantMoeda;
    }

    public void setTxtQuantMoeda(JTextField txtQuantMoeda) {
        this.txtQuantMoeda = txtQuantMoeda;
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReaisRes = new javax.swing.JLabel();
        lblCompra = new javax.swing.JLabel();
        lblCotacaoT = new javax.swing.JLabel();
        txtQuantMoeda = new javax.swing.JTextField();
        lblQuant = new javax.swing.JLabel();
        lblDecisao = new javax.swing.JLabel();
        lblCotacao = new javax.swing.JLabel();
        txtMoeda = new javax.swing.JTextField();
        btCompra = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        lblReaisRes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCompra.setFont(new java.awt.Font("Book Antiqua", 3, 36)); // NOI18N
        lblCompra.setText("Comprar Criptomoedas");

        lblCotacaoT.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        lblCotacaoT.setText("Cotações:");

        txtQuantMoeda.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        lblQuant.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        lblQuant.setText("Quantidade:");

        lblDecisao.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        lblDecisao.setText("Qual moeda deseja comprar?");

        lblCotacao.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        lblCotacao.setText("-");

        txtMoeda.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        btCompra.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        btCompra.setText("Comprar");
        btCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCompraActionPerformed(evt);
            }
        });

        jMenuMenu.setText("Menu");

        jMenuItem1.setText("menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuMenu.add(jMenuItem1);

        jMenuBar1.add(jMenuMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCotacao, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMoeda, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblQuant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantMoeda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblCompra))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDecisao))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCotacaoT)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDecisao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMoeda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuant)
                    .addComponent(txtQuantMoeda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblCotacaoT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCotacao, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        BemVindoUsuario b = new BemVindoUsuario(investidor);
        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCompraActionPerformed
        control.compraMoeda();
    }//GEN-LAST:event_btCompraActionPerformed
//
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ComprarCripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ComprarCripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ComprarCripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ComprarCripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ComprarCripto().setVisible(true);
//            }
//        });
//    }
    private Investidor investidor; 
    private ControllerCompraCripto control;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCompra;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jMenuMenu;
    private javax.swing.JLabel lblCompra;
    private javax.swing.JLabel lblCotacao;
    private javax.swing.JLabel lblCotacaoT;
    private javax.swing.JLabel lblDecisao;
    private javax.swing.JLabel lblQuant;
    private javax.swing.JLabel lblReaisRes;
    private javax.swing.JTextField txtMoeda;
    private javax.swing.JTextField txtQuantMoeda;
    // End of variables declaration//GEN-END:variables
}
